In [1]:
pip install tensorflow

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
pip install tensorflow-gpu

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 578.0 MB 14 kB/s 
     |████████████████████████████████| 5.9 MB 44.9 MB/s 
     |████████████████████████████████| 438 kB 52.6 MB/s 
     |████████████████████████████████| 1.7 MB 48.7 MB/s 
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.8.0
    Uninstalling tensorflow-estimator-2.8.0:
      Successfully uninstalled tensorflow-estimator-2.8.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.8.0
    Uninstalling tensorboard-2.8.0:
      Successfully uninstalled tensorboard-2.8.0
  Attempting uninstall: keras
    Found existing installation: keras 2.8.0
    Uninstalling keras-2.8.0:
      Successfully uninstalled keras-2.8.0
  Attempting uninstall: gast
    Found existing installation: gast 0.5.3
    Uninstalling gast-0.5.3:
      Successfully uninstalled gast-0.5

In [2]:
import tensorflow as tf

In [3]:
hello = tf.constant('Hello, Tensorflow!')

In [4]:
sess=tf.compat.v1.Session()

In [5]:
print(sess.run(hello))

RuntimeError: ignored

In [6]:
pip install --upgrade pip

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 2.1 MB 9.3 MB/s 
  Attempting uninstall: pip
    Found existing installation: pip 21.1.3
    Uninstalling pip-21.1.3:
      Successfully uninstalled pip-21.1.3


In [ ]:
pip install tensorflow

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 462.3/462.3 kB 12.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.8/5.8 MB 59.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 70.2 MB/s eta 0:00:00
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.10.0
    Uninstalling tensorflow-estimator-2.10.0:
      Successfully uninstalled tensorflow-estimator-2.10.0
  Attempting uninstall: keras
    Found existing installation: keras 2.10.0
    Uninstalling keras-2.10.0:
      Successfully uninstalled keras-2.10.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.10.1
    Uninstalling tensorboard-2.10.1:
      Successfully uninstalled tensorboard-2.10.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is 

In [7]:
tf.compat.v1.get_default_session()


In [9]:
import numpy as np

In [10]:
tensor_1d=np.array([1.3,1,4.0,23.99])

In [11]:
print(tensor_1d)

[ 1.3   1.    4.   23.99]


In [ ]:
######

In [12]:
matrix1=np.array([(2,2,2),(2,2,2),(2,2,2)],dtype='int32')

In [13]:
matrix2=np.array([(1,1,1),(1,1,1),(1,1,1)],dtype='int32')

In [14]:
print(matrix1)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [15]:
print(matrix2)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [16]:
matrix1=tf.constant(matrix1)

In [17]:
matrix2=tf.constant(matrix2)

In [18]:
matrix_product=tf.matmul(matrix1,matrix2)

In [19]:
matrix_product

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]], dtype=int32)>

In [21]:
matrix_sum = tf.add(matrix1,matrix2)

In [22]:
matrix_sum

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]], dtype=int32)>

In [23]:
matrix_3 = np.array([(2,7,2),(1,4,2),(9,0,2)],dtype = 'float32')

In [24]:
print (matrix_3)

[[2. 7. 2.]
 [1. 4. 2.]
 [9. 0. 2.]]


In [25]:
matrix_det = tf.linalg.det(matrix_3,name=None)

In [27]:
## with tf.Session() as sess:
  result1 = sess.run(matrix_product)
  result2 = sess.run(matrix_sum)
  result3 = sess.run(matrix_det)

IndentationError: ignored